version: '3'
services:
  warren-db:
    container_name: warren-db
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - ./config/postgres/database.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 15s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: root
  warren-bank-api:
    container_name: warren-bank-api
    build: ./applications/warren-api-test
    volumes:
      - ./applications/warren-api-test:/app
    ports:
      - 3333:3333
    depends_on:
      warren-db:
        condition: service_healthy
  warren-client:
    stdin_open: true
    container_name: warren-client
    build: ./applications/warren-client-test
    ports:
      - "3380:80"
    volumes:
      - "./applications/warren-client-test:/app"
      - ./config/client/nginx.conf:/etc/nginx/nginx.conf

